# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.17.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=net.cat_metalhead.stringless
archives_base_name=stringless

# Dependencies
fabric_version=0.155.2+26.1.2
modmenu_version=3rsoV1bk
yacl_version=3.9.6+26.1-fabric
sodium_version=mc26.1.1-0.8.9-fabric